### ISSUE TITLE
出现了这种问题，是有什么东西没配置好吗？

### ISSUE THREAD

**Issue by h1storreson** [Ghauster/BilibiliCommentScraper#10]
测试cookies文件是否已获取。若无，请在弹出的窗口中登录b站账号，登录完成后，窗口将关闭；若有，窗口会立即关闭
Traceback (most recent call last):
  File "C:\Users\mason\BilibiliCommentScraper\Bilicomment.py", line 474, in <module>
    main()
  File "C:\Users\mason\BilibiliCommentScraper\Bilicomment.py", line 302, in main
    driver = webdriver.Chrome(service=Service(executable_path=ChromeDriverManager().install()))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\F\programs\python\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\F\programs\python\Lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\F\programs\python\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\F\programs\python\Lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\F\programs\python\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Cyiming** [comment]
一样

**Comment by MrL646** [comment]
试着重新安装一下依赖：
`pip install selenium==4.8.3 beautifulsoup4==4.11.1 webdriver-manager`
此方法在Windows 11 + Python 3.9.18下测试可用
记得安装[Chrome](https://www.google.cn/intl/zh-CN/chrome/)（Chromium和Edge都不行）

**Comment by MrL646** [comment]
Python 3.12也行
