### ISSUE TITLE
出现bug 

### ISSUE THREAD

**Issue by cauzp** [Ghauster/BilibiliCommentScraper#16]
测试cookies文件是否已获取。若无，请在弹出的窗口中登录b站账号，登录完成后，窗口将关闭；若有，窗口会立即关闭

DevTools listening on ws://127.0.0.1:64354/devtools/browser/69943c7b-cfa3-4429-9edd-1763ae4d6d6f
Traceback (most recent call last):
  File "c:\Users\zpzxm\OneDrive - HKUST (Guangzhou)\Desktop\BilibiliCommentScraper-main\Bilicomment.py", line 474, in <module>
    main()
  File "c:\Users\zpzxm\OneDrive - HKUST (Guangzhou)\Desktop\BilibiliCommentScraper-main\Bilicomment.py", line 304, in main
    if not load_cookies(driver, cookies_file):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zpzxm\OneDrive - HKUST (Guangzhou)\Desktop\BilibiliCommentScraper-main\Bilicomment.py", line 55, in load_cookies
    driver.add_cookie(cookie)
  File "C:\Users\zpzxm\Miniconda3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 725, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "C:\Users\zpzxm\Miniconda3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\zpzxm\Miniconda3\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=124.0.6367.208)
Stacktrace:
        GetHandleVerifier [0x0052C113+48259]
        (No symbol) [0x004BCA41]
        (No symbol) [0x003B0A17]
        (No symbol) [0x0043987B]
        (No symbol) [0x00410D9C]
        (No symbol) [0x00429B9C]
        (No symbol) [0x00410B36]
        (No symbol) [0x003E570D]
        (No symbol) [0x003E62CD]
        GetHandleVerifier [0x007E65A3+2908435]
        GetHandleVerifier [0x00823BBB+3159851]
        GetHandleVerifier [0x005C50CB+674875]
        GetHandleVerifier [0x005CB28C+699900]
        (No symbol) [0x004C6244]
        (No symbol) [0x004C2298]
        (No symbol) [0x004C242C]
        (No symbol) [0x004B4BB0]
        BaseThreadInitThunk [0x76527BA9+25]
        RtlInitializeExceptionChain [0x7726BE3B+107]
        RtlClearBits [0x7726BDBF+191]

**Comment by cauzp** [comment]
i have fixed this bug.
if you encounter this probelm again, just take place "space.bilibili.com" with "www.bilibili.com"

**Comment by auskenzhang2** [comment]
same bug but not fixed with this change

**Comment by cauzp** [comment]
> same bug but not fixed with this change

maybe you can reference the bilibili api v2 and generate another script, this script seemly out of date.
