### ISSUE TITLE
不是有效的Win32应用程序

### ISSUE THREAD

**Issue by Harvey-Walker** [Ghauster/BilibiliCommentScraper#18]
我在运行程序时出现如下报错：
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\BilibiliCommentScraper\Bilicomment.py", line 475, in <module>
    main()
  **File "C:\Users\Administrator\Desktop\BilibiliCommentScraper\Bilicomment.py", line 303, in main
    driver = webdriver.Chrome(service=Service(executable_path=ChromeDriverManager().install()))**
  File "D:\Python3.12.1\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "D:\Python3.12.1\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 101, in __init__
    self.service.start()
  File "D:\Python3.12.1\Lib\site-packages\selenium\webdriver\common\service.py", line 90, in start
    self._start_process(self.path)
  File "D:\Python3.12.1\Lib\site-packages\selenium\webdriver\common\service.py", line 203, in _start_process
    self.process = subprocess.Popen(
  File "D:\Python3.12.1\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python3.12.1\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
**OSError: [WinError 193] %1 不是有效的 Win32 应用程序。**

**Comment by Marvingao** [comment]
webdriver的问题吧，你自己写一个看能不能打开网页
